// paste your entire JSON array below this line
const rawDeck = 
[
  {
    "num": 0,
    "face": "0603170325589_00_678029bbc55011a335aa0623a5fbd863.jpg",
    "card title": "the fool",
    "arcana": "major",
    "suit": "major",
    "core themes": "beginnings, innocence, leap of faith",
    "upright keywords": "new journey, spontaneity, risk, freedom, trust, openness",
    "reversed keywords": "recklessness, naivety, poor planning, hesitation, fear of starting",
    "shadow expression": "avoiding responsibility under the mask of "freedom",
    "growth edge": "trust the leap, but pack wisely",
    "element": "archetypal"
  },
  {
    "num": 1,
    "face": "0603170325589_02_1affc857cacbf5a0ff6ead63d66211ea.jpg",
    "card title": "the magician",
    "arcana": "major",
    "suit": "major",
    "core themes": "manifestation, personal power",
    "upright keywords": "skill, focus, action, confidence, resourcefulness",
    "reversed keywords": "manipulation, scattered energy, insecurity, unused potential",
    "shadow expression": "using influence to control instead of create",
    "growth edge": "direct your will deliberately",
    "element": "archetypal"
  },
  {
    "num": 2,
    "face": "0603170325589_03_0ddacb930338683e6aae222a529e79f1.jpg",
    "card title": "the high priestess",
    "arcana": "major",
    "suit": "major",
    "core themes": "inner knowing, intuition",
    "upright keywords": "mystery, subconscious, insight, silence, wisdom",
    "reversed keywords": "blocked intuition, secrets, confusion, emotional suppression",
    "shadow expression": "withholding truth to maintain power",
    "growth edge": "trust what you already know",
    "element": "archetypal"
  },
  {
    "num": 3,
    "face": "0603170325589_04_19dd16bc6fda522034e722acc866cd03.jpg",
    "card title": "the emperess",
    "arcana": "major",
    "suit": "major",
    "core themes": "creation, nurture",
    "upright keywords": "abundance, fertility, beauty, care, growth",
    "reversed keywords": "overgiving, smothering, neglect, creative block",
    "shadow expression": "losing self while nurturing others",
    "growth edge": "care for yourself as fiercely as others",
    "element": "archetypal"
  },
  {
    "num": 4,
    "face": "0603170325589_05_c574474b6f14b2bd02d87815f06c59cd.jpg",
    "card title": "the emperor",
    "arcana": "major",
    "suit": "major",
    "core themes": "authority, structure",
    "upright keywords": "stability, leadership, boundaries, order, discipline",
    "reversed keywords": "rigidity, control issues, domination, instability",
    "shadow expression": "mistaking control for strength",
    "growth edge": "lead without suppressing",
    "element": "archetypal"
  },
  {
    "num": 5,
    "face": "0603170325589_06_37da9a540c0b9bc51355f2e2c19943b9.jpg",
    "card title": "the heirophant",
    "arcana": "major",
    "suit": "major",
    "core themes": "belief systems, tradition",
    "upright keywords": "institutions, conformity, mentorship, spiritual structure",
    "reversed keywords": "rebellion, dogma, blind faith, outdated rules",
    "shadow expression": "hiding behind tradition to avoid growth",
    "growth edge": "question what you inherited",
    "element": "archetypal"
  },
  {
    "num": 6,
    "face": "0603170325589_07_a7c10a5faaf2a2a4de0075d5ea71ad3b.jpg",
    "card title": "the lovers",
    "arcana": "major",
    "suit": "major",
    "core themes": "alignment, choices, union",
    "upright keywords": "partnership, values, harmony, unity, commitment",
    "reversed keywords": "misalignment, imbalance, temptation, discord",
    "shadow expression": "choosing desire over integrity",
    "growth edge": "choose in alignment with your values",
    "element": "archetypal"
  },
  {
    "num": 7,
    "face": "0603170325589_08_1e89a2cb614d15fd1e231269ea2cc30c.jpg",
    "card title": "the chariot",
    "arcana": "major",
    "suit": "major",
    "core themes": "direction, willpower",
    "upright keywords": "determination, victory, ambition, control, forward movement",
    "reversed keywords": "lack of direction, aggression, scattered effort, burnout",
    "shadow expression": "forcing progress without emotional alignment",
    "growth edge": "move with purpose, not pressure",
    "element": "archetypal"
  },
  {
    "num": 8,
    "face": "0603170325589_09_1b0fc07411416100fd85ec05b4b8246a.jpg",
    "card title": "strength",
    "arcana": "major",
    "suit": "major",
    "core themes": "inner power, resilience",
    "upright keywords": "courage, patience, compassion, endurance, calm control",
    "reversed keywords": "self-doubt, weakness, insecurity, suppressed anger",
    "shadow expression": "confusing dominance with strength",
    "growth edge": "gentleness is not weakness",
    "element": "archetypal"
  },
  {
    "num": 9,
    "face": "0603170325589_10_3eaa96f92c8b013f8eb84a358d7eb100.jpg",
    "card title": "the hermit",
    "arcana": "major",
    "suit": "major",
    "core themes": "introspection, solitude",
    "upright keywords": "reflection, wisdom, withdrawal, guidance, inner search",
    "reversed keywords": "isolation, loneliness, avoidance, withdrawal from growth",
    "shadow expression": "hiding from life under the guise of solitude",
    "growth edge": "seek answers within, then return to the world",
    "element": "archetypal"
  },
  {
    "num": 10,
    "face": "0603170325589_11_899cd14941a67c67901187755f1eef94.jpg",
    "card title": "wheel of fortune",
    "arcana": "major",
    "suit": "major",
    "core themes": "cycles, fate",
    "upright keywords": "change, destiny, turning point, luck, karma",
    "reversed keywords": "resistance to change, bad luck, stagnation, lack of control",
    "shadow expression": "blaming fate instead of adapting",
    "growth edge": "adapt to the turning of the wheel",
    "element": "archetypal"
  },
  {
    "num": 11,
    "face": "0603170325589_12_c7de472fc407322bc8e95c972546fd12.jpg",
    "card title": "justice",
    "arcana": "major",
    "suit": "major",
    "core themes": "balance, truth",
    "upright keywords": "fairness, accountability, law, clarity, cause and effect",
    "reversed keywords": "dishonesty, unfairness, denial, imbalance",
    "shadow expression": "avoiding responsibility for consequences",
    "growth edge": "act with integrity",
    "element": "archetypal"
  },
  {
    "num": 12,
    "face": "0603170325589_13_b9b7cb5f226c779056861c60dd9d7883.jpg",
    "card title": "the hanged man",
    "arcana": "major",
    "suit": "major",
    "core themes": "leap of faith, perspective, surrender",
    "upright keywords": "pause, sacrifice, new perspective, release, patience",
    "reversed keywords": "stalling, resistance, martyrdom, delay",
    "shadow expression": "refusing to let go when necessary",
    "growth edge": "sometimes surrender is strength",
    "element": "archetypal"
  },
  {
    "num": 13,
    "face": "0603170325589_14_2fc4425a191475c739cfb030b43763f1.jpg",
    "card title": "death",
    "arcana": "major",
    "suit": "major",
    "core themes": "endings, transformation",
    "upright keywords": "rebirth, transition, release, renewal, closure",
    "reversed keywords": "fear of change, clinging, stagnation, resistance",
    "shadow expression": "holding onto what is already gone",
    "growth edge": "let endings create space for beginnings",
    "element": "archetypal"
  },
  {
    "num": 14,
    "face": "0603170325589_15_7bea7f83bb7093f18a41bba46f1b7427.jpg",
    "card title": "temperance",
    "arcana": "major",
    "suit": "major",
    "core themes": "balance, integration",
    "upright keywords": "moderation, harmony, healing, blending, patience",
    "reversed keywords": "excess, imbalance, discord, extremes",
    "shadow expression": "avoiding moderation in pursuit of intensity",
    "growth edge": "blend opposing forces",
    "element": "archetypal"
  },
  {
    "num": 15,
    "face": "0603170325589_16_8f5e336db5557771ee63c1aa2152ea6d.jpg",
    "card title": "the devil",
    "arcana": "major",
    "suit": "major",
    "core themes": "attachment, shadow",
    "upright keywords": "addiction, control, materialism, temptation, bondage",
    "reversed keywords": "release, awareness, breaking chains, reclaiming power",
    "shadow expression": "mistaking attachment for security",
    "growth edge": "recognize what holds you",
    "element": "archetypal"
  },
  {
    "num": 16,
    "face": "0603170325589_17_895483f2f33dc90c502f9bd405d9f630.jpg",
    "card title": "the tower",
    "arcana": "major",
    "suit": "major",
    "core themes": "revelation, upheaval",
    "upright keywords": "sudden change, collapse, awakening, disruption, truth",
    "reversed keywords": "delayed disaster, fear of change, internal crisis",
    "shadow expression": "ignoring cracks until collapse is forced",
    "growth edge": "let false structures fall",
    "element": "archetypal"
  },
  {
    "num": 17,
    "face": "0603170325589_18_1b8a346488fdf4ff9a6933d4db7d7d37.jpg",
    "card title": "the star",
    "arcana": "major",
    "suit": "major",
    "core themes": "hope, renewal",
    "upright keywords": "faith, healing, optimism, inspiration, guidance",
    "reversed keywords": "doubt, discouragement, lack of faith, disconnection",
    "shadow expression": "losing belief after hardship",
    "growth edge": "trust the quiet light",
    "element": "archetypal"
  },
  {
    "num": 18,
    "face": "0603170325589_19_1ed7a0f351a0622323a409be4746c589.jpg",
    "card title": "the moon",
    "arcana": "major",
    "suit": "major",
    "core themes": "illusion, subconscious",
    "upright keywords": "uncertainty, intuition, dreams, confusion, hidden truths",
    "reversed keywords": "clarity, truth revealed, fear released, understanding",
    "shadow expression": "letting fear distort perception",
    "growth edge": "face what lurks beneath",
    "element": "archetypal"
  },
  {
    "num": 19,
    "face": "0603170325589_20_16346c2a033548179ec5e6c58fe2dfb3.jpg",
    "card title": "the sun",
    "arcana": "major",
    "suit": "major",
    "core themes": "clarity, joy",
    "upright keywords": "success, vitality, happiness, confidence, positivity",
    "reversed keywords": "temporary sadness, ego, unrealistic optimism",
    "shadow expression": "performing happiness instead of feeling it",
    "growth edge": "allow yourself to shine",
    "element": "archetypal"
  },
  {
    "num": 20,
    "face": "0603170325589_21_800272d9e2f4266c7867ede1e8a40f9b.jpg",
    "card title": "judgement",
    "arcana": "major",
    "suit": "major",
    "core themes": "awakening, reckoning",
    "upright keywords": "rebirth, self-evaluation, calling, transformation, accountability",
    "reversed keywords": "self-doubt, avoidance, fear of change, stagnation",
    "shadow expression": "refusing to answer your calling",
    "growth edge": "rise to your higher self",
    "element": "archetypal"
  },
  {
    "num": 21,
    "face": "0603170325589_22_8b820d52bca7cf5a56ab79116aab4787.jpg",
    "card title": "the world",
    "arcana": "major",
    "suit": "major",
    "core themes": "completion, fulfillment",
    "upright keywords": "achievement, wholeness, integration, success, closure",
    "reversed keywords": "unfinished business, delay, lack of closure",
    "shadow expression": "fearing completion because it requires change",
    "growth edge": "honor the cycle’s end",
    "element": "archetypal"
  },
  {
    "num": 22,
    "face": "0603170325589_65_88c2404780c00becee3d87e532de4514.jpg",
    "card title": "ace of pentacles",
    "arcana": "minor",
    "suit": "pentacles",
    "core themes": "opportunity, stability",
    "upright keywords": "new venture, prosperity, security, manifestation, investment",
    "reversed keywords": "missed opportunity, instability, poor planning, financial delay",
    "shadow expression": "fearing growth because it requires responsibility",
    "growth edge": "plant what you want to harvest",
    "element": "earth"
  },
  {
    "num": 23,
    "face": "0603170325589_66_20175148e8d46abd938d016572de27b2.jpg",
    "card title": "two of pentacles",
    "arcana": "minor",
    "suit": "pentacles",
    "core themes": "adaptability, balance",
    "upright keywords": "juggling, flexibility, priorities, time management, decision",
    "reversed keywords": "overwhelm, imbalance, disorganization, stress",
    "shadow expression": "pretending everything is under control",
    "growth edge": "simplify and prioritize",
    "element": "earth"
  },
  {
    "num": 24,
    "face": "0603170325589_67_b99fb44507245d7b4d0a0bd11c71982d.jpg",
    "card title": "three  of pentacles",
    "arcana": "minor",
    "suit": "pentacles",
    "core themes": "collaboration, effort",
    "upright keywords": "teamwork, skill, learning, cooperation, progress",
    "reversed keywords": "miscommunication, lack of teamwork, mediocrity, conflict",
    "shadow expression": "seeking recognition without contribution",
    "growth edge": "build with others",
    "element": "earth"
  },
  {
    "num": 25,
    "face": "0603170325589_68_e8a5a5dacfdc5dc4736be581d1e8a740.jpg",
    "card title": "four of pentacles",
    "arcana": "minor",
    "suit": "pentacles",
    "core themes": "control, security",
    "upright keywords": "holding on, protection, stability, possessiveness, caution",
    "reversed keywords": "greed, fear of loss, financial insecurity, release",
    "shadow expression": "clinging to avoid vulnerability",
    "growth edge": "trust enough to loosen your grip",
    "element": "earth"
  },
  {
    "num": 26,
    "face": "0603170325589_69_3058847baca9fe5d934faa66fcf11ad6.jpg",
    "card title": "five of pentacles",
    "arcana": "minor",
    "suit": "pentacles",
    "core themes": "hardship, scarcity",
    "upright keywords": "financial loss, isolation, struggle, insecurity, worry",
    "reversed keywords": "recovery, support, renewal, improvement",
    "shadow expression": "believing you must struggle alone",
    "growth edge": "accept help when offered",
    "element": "earth"
  },
  {
    "num": 27,
    "face": "0603170325589_70_b92bf0d485241121623f30f035c4438c.jpg",
    "card title": "six of pentacles",
    "arcana": "minor",
    "suit": "pentacles",
    "core themes": "exchange, generosity",
    "upright keywords": "giving, receiving, charity, fairness, support",
    "reversed keywords": "debt, imbalance, strings attached, inequality",
    "shadow expression": "giving to gain control",
    "growth edge": "give and receive with integrity",
    "element": "earth"
  },
  {
    "num": 28,
    "face": "0603170325589_71_1514302647d4792da008c30ae8546697.jpg",
    "card title": "seven of pentacles",
    "arcana": "minor",
    "suit": "pentacles",
    "core themes": "assessment, patience",
    "upright keywords": "evaluation, long-term growth, reflection, investment, waiting",
    "reversed keywords": "impatience, frustration, poor results, lack of reward",
    "shadow expression": "expecting growth without effort",
    "growth edge": "trust steady progress",
    "element": "earth"
  },
  {
    "num": 29,
    "face": "0603170325589_72_d4d7230f841919802d1a1e85990e9210.jpg",
    "card title": "eight of pentacles",
    "arcana": "minor",
    "suit": "pentacles",
    "core themes": "diligence, mastery",
    "upright keywords": "skill-building, focus, dedication, practice, craftsmanship",
    "reversed keywords": "perfectionism, boredom, lack of focus, low quality",
    "shadow expression": "working to avoid emotional life",
    "growth edge": "commit to improvement",
    "element": "earth"
  },
  {
    "num": 30,
    "face": "0603170325589_73_a9ea25216d7a372f63b4177ff76f5bd6.jpg",
    "card title": "nine of pentacles",
    "arcana": "minor",
    "suit": "pentacles",
    "core themes": "abundance, independence",
    "upright keywords": "self-sufficiency, luxury, achievement, confidence, comfort",
    "reversed keywords": "dependence, insecurity, financial instability, isolation",
    "shadow expression": "equating worth with wealth",
    "growth edge": "enjoy what you’ve built",
    "element": "earth"
  },
  {
    "num": 31,
    "face": "0603170325589_74_c76f6b123224075336f2b372196eef4f.jpg",
    "card title": "ten of pentacles",
    "arcana": "minor",
    "suit": "pentacles",
    "core themes": "legacy, security",
    "upright keywords": "wealth, family stability, long-term success, inheritance, tradition",
    "reversed keywords": "financial instability, family conflict, loss, insecurity",
    "shadow expression": "valuing status over connection",
    "growth edge": "build what lasts",
    "element": "earth"
  },
  {
    "num": 32,
    "face": "0603170325589_75_0f41f086308b4227c36d4e34a300336c.jpg",
    "card title": "page of pentacles",
    "arcana": "minor",
    "suit": "pentacles",
    "core themes": "ambition, learning",
    "upright keywords": "new study, opportunity, curiosity, planning, discipline",
    "reversed keywords": "laziness, procrastination, lack of focus, immaturity",
    "shadow expression": "wanting results without effort",
    "growth edge": "start small and stay consistent",
    "element": "earth"
  },
  {
    "num": 33,
    "face": "0603170325589_76_9f2041a8543dce108b46a9f2a2ced143.jpg",
    "card title": "knight of pentacles",
    "arcana": "minor",
    "suit": "pentacles",
    "core themes": "discipline, persistence",
    "upright keywords": "reliability, hard work, routine, responsibility, commitment",
    "reversed keywords": "stubbornness, monotony, resistance to change, rigidity",
    "shadow expression": "mistaking stubbornness for stability",
    "growth edge": "stay steady but flexible",
    "element": "earth"
  },
  {
    "num": 34,
    "face": "0603170325589_77_e264de9d0c24d5e1d6ea510e00a4305b.jpg",
    "card title": "queen of pentacles",
    "arcana": "minor",
    "suit": "pentacles",
    "core themes": "nurture, practicality",
    "upright keywords": "stability, generosity, resourcefulness, comfort, care",
    "reversed keywords": "overwork, insecurity, neglect, material focus",
    "shadow expression": "measuring love through productivity",
    "growth edge": "balance care for others with care for self",
    "element": "earth"
  },
  {
    "num": 35,
    "face": "0603170325589_78_f75e6d6ed0aa6c6290e1e87eb205ab34.jpg",
    "card title": "king of pentacles",
    "arcana": "minor",
    "suit": "pentacles",
    "core themes": "authority, prosperity",
    "upright keywords": "success, leadership, wealth, stability, security",
    "reversed keywords": "greed, corruption, control, material obsession",
    "shadow expression": "valuing power over integrity",
    "growth edge": "lead with grounded integrity",
    "element": "earth"
  },
  {
    "num": 36,
    "face": "0603170325589_51_6faa9b3750f79b8b9ba79808c9f129c7.jpg",
    "card title": "ace of swords",
    "arcana": "minor",
    "suit": "swords",
    "core themes": "clarity, truth",
    "upright keywords": "insight, breakthrough, honesty, communication, mental focus",
    "reversed keywords": "confusion, misinformation, clouded judgment, miscommunication",
    "shadow expression": "weaponizing truth to wound",
    "growth edge": "speak with precision and integrity",
    "element": "air"
  },
  {
    "num": 37,
    "face": "0603170325589_52_af4ea8bab3e734f8a23998ef0924fbeb.jpg",
    "card title": "two of swords",
    "arcana": "minor",
    "suit": "swords",
    "core themes": "avoidance, indecision",
    "upright keywords": "stalemate, denial, blocked emotions, difficult choice",
    "reversed keywords": "clarity, truth revealed, decision made, emotional release",
    "shadow expression": "refusing to face reality",
    "growth edge": "remove the blindfold",
    "element": "air"
  },
  {
    "num": 38,
    "face": "0603170325589_53_536f2a13a6a3386c5a8e80f47f425da9.jpg",
    "card title": "three of swords",
    "arcana": "minor",
    "suit": "swords",
    "core themes": "betrayal, heartbreak",
    "upright keywords": "pain, sorrow, grief, separation, emotional wound",
    "reversed keywords": "healing, forgiveness, recovery, acceptance",
    "shadow expression": "reopening wounds to stay attached",
    "growth edge": "let pain transform you",
    "element": "air"
  },
  {
    "num": 39,
    "face": "0603170325589_54_efa56e98b81e6f8a7d2f818c0fa87b7a.jpg",
    "card title": "four of swords",
    "arcana": "minor",
    "suit": "swords",
    "core themes": "recovery, rest",
    "upright keywords": "pause, retreat, healing, contemplation, restoration",
    "reversed keywords": "burnout, restlessness, exhaustion, avoidance",
    "shadow expression": "ignoring the need for rest",
    "growth edge": "restore before returning",
    "element": "air"
  },
  {
    "num": 40,
    "face": "0603170325589_55_b912951f62204a57a59212a9523c0bd9.jpg",
    "card title": "five of swords",
    "arcana": "minor",
    "suit": "swords",
    "core themes": "conflict, defeat",
    "upright keywords": "tension, hostility, loss, ego, betrayal",
    "reversed keywords": "resolution, reconciliation, regret, compromise",
    "shadow expression": "winning at the cost of integrity",
    "growth edge": "choose peace over ego",
    "element": "air"
  },
  {
    "num": 41,
    "face": "0603170325589_56_98db19f0fe8ed325fd5f33864f7ae946.jpg",
    "card title": "six of swords",
    "arcana": "minor",
    "suit": "swords",
    "core themes": "healing, transition",
    "upright keywords": "moving on, progress, recovery, passage, relief",
    "reversed keywords": "resistance, unfinished business, stagnation",
    "shadow expression": "carrying baggage into new chapters",
    "growth edge": "leave what no longer serves",
    "element": "air"
  },
  {
    "num": 42,
    "face": "0603170325589_57_e4e579f414d5d392a2161f70ecd77096.jpg",
    "card title": "seven of swords",
    "arcana": "minor",
    "suit": "swords",
    "core themes": "deception, strategy",
    "upright keywords": "secrecy, betrayal, cunning, dishonesty, independence",
    "reversed keywords": "confession, exposure, accountability, truth revealed",
    "shadow expression": "self-deception disguised as cleverness",
    "growth edge": "act with integrity",
    "element": "air"
  },
  {
    "num": 43,
    "face": "0603170325589_58_2ffa141abd999c386724aa67607d32ba.jpg",
    "card title": "eight of swords",
    "arcana": "minor",
    "suit": "swords",
    "core themes": "fear, restriction",
    "upright keywords": "limitation, self-doubt, trapped, victim mindset, anxiety",
    "reversed keywords": "freedom, empowerment, self-awareness, release",
    "shadow expression": "believing you are powerless",
    "growth edge": "challenge limiting beliefs",
    "element": "air"
  },
  {
    "num": 44,
    "face": "0603170325589_59_bdda863a9afcf0dce618a85df877e499.jpg",
    "card title": "nine of swords",
    "arcana": "minor",
    "suit": "swords",
    "core themes": "anxiety, guilt",
    "upright keywords": "worry, stress, insomnia, regret, mental anguish",
    "reversed keywords": "relief, healing, confronting fears, forgiveness",
    "shadow expression": "magnifying fears beyond reality",
    "growth edge": "face what haunts you",
    "element": "air"
  },
  {
    "num": 45,
    "face": "0603170325589_60_1bec875cee48f1c917978096309b6208.jpg",
    "card title": "ten of swords",
    "arcana": "minor",
    "suit": "swords",
    "core themes": "endings, ruin",
    "upright keywords": "betrayal, collapse, painful ending, defeat, crisis",
    "reversed keywords": "recovery, resilience, survival, rebirth",
    "shadow expression": "clinging to victimhood",
    "growth edge": "rise after the fall",
    "element": "air"
  },
  {
    "num": 46,
    "face": "0603170325589_61_8e8fb4f0d35590c06424ad86100eaf14.jpg",
    "card title": "page of swords",
    "arcana": "minor",
    "suit": "swords",
    "core themes": "curiosity, vigilance",
    "upright keywords": "inquiry, communication, alertness, learning, ideas",
    "reversed keywords": "gossip, immaturity, scattered thoughts, defensiveness",
    "shadow expression": "speaking without understanding",
    "growth edge": "listen before reacting",
    "element": "air"
  },
  {
    "num": 47,
    "face": "0603170325589_62_ae60212f4337fb84cad553620100e6a5.jpg",
    "card title": "knight of swords",
    "arcana": "minor",
    "suit": "swords",
    "core themes": "ambition, intensity",
    "upright keywords": "drive, action, assertiveness, speed, determination",
    "reversed keywords": "recklessness, aggression, impulsiveness, hostility",
    "shadow expression": "charging ahead without thought",
    "growth edge": "temper action with awareness",
    "element": "air"
  },
  {
    "num": 48,
    "face": "0603170325589_63_6f6fc92430a03bf16e8e38f0696fb10b.jpg",
    "card title": "queen of swords",
    "arcana": "minor",
    "suit": "swords",
    "core themes": "clarity, independence",
    "upright keywords": "honesty, perception, intellect, truth, discernment",
    "reversed keywords": "coldness, bitterness, harsh judgment, isolation",
    "shadow expression": "using intellect to distance from emotion",
    "growth edge": "balance truth with compassion",
    "element": "air"
  },
  {
    "num": 49,
    "face": "0603170325589_64_047d5b3338f27d3ad5dbfb27b4347f17.jpg",
    "card title": "king of swords",
    "arcana": "minor",
    "suit": "swords",
    "core themes": "authority, intellect",
    "upright keywords": "logic, leadership, strategy, fairness, discipline",
    "reversed keywords": "manipulation, tyranny, cruelty, rigidity",
    "shadow expression": "prioritizing control over justice",
    "growth edge": "lead with wisdom and fairness",
    "element": "air"
  },
  {
    "num": 50,
    "face": "0603170325589_37_f82ba2b10d25c69f574f0d0cb0fe975e.jpg",
    "card title": "ace of cups",
    "arcana": "minor",
    "suit": "cups",
    "core themes": "love, renewal",
    "upright keywords": "new love, compassion, emotional renewal, intimacy, openness",
    "reversed keywords": "emotional blockage, self-love issues, suppressed feelings, emptiness",
    "shadow expression": "seeking love externally while neglecting self",
    "growth edge": "let yourself feel fully",
    "element": "water"
  },
  {
    "num": 51,
    "face": "0603170325589_38_b1071086789d14cf28db5c78c7af73ce.jpg",
    "card title": "two of cups",
    "arcana": "minor",
    "suit": "cups",
    "core themes": "connection, partnership",
    "upright keywords": "union, harmony, attraction, mutual respect, emotional bond",
    "reversed keywords": "imbalance, miscommunication, tension, emotional distance",
    "shadow expression": "projecting ideals onto another",
    "growth edge": "build connection on honesty",
    "element": "water"
  },
  {
    "num": 52,
    "face": "0603170325589_39_5703c98740de1e53219f1ec654df9b6f.jpg",
    "card title": "three of cups",
    "arcana": "minor",
    "suit": "cups",
    "core themes": "celebration, community",
    "upright keywords": "friendship, joy, support, reunion, shared happiness",
    "reversed keywords": "gossip, excess, overindulgence, social tension",
    "shadow expression": "seeking validation through social approval",
    "growth edge": "celebrate without losing balance",
    "element": "water"
  },
  {
    "num": 53,
    "face": "0603170325589_40_245d0eaebca2720b429325e07f88cc62.jpg",
    "card title": "four of cups",
    "arcana": "minor",
    "suit": "cups",
    "core themes": "apathy, reevaluation",
    "upright keywords": "discontent, contemplation, boredom, withdrawal, missed opportunity",
    "reversed keywords": "renewed interest, awareness, acceptance, clarity",
    "shadow expression": "rejecting blessings out of frustration",
    "growth edge": "recognize what is being offered",
    "element": "water"
  },
  {
    "num": 54,
    "face": "0603170325589_41_2c9641d1278e6d26efdd26129602f6d5.jpg",
    "card title": "five of cups",
    "arcana": "minor",
    "suit": "cups",
    "core themes": "grief, regret",
    "upright keywords": "loss, disappointment, sorrow, emotional setback",
    "reversed keywords": "healing, acceptance, moving forward, forgiveness",
    "shadow expression": "dwelling on what is gone",
    "growth edge": "turn toward what remains",
    "element": "water"
  },
  {
    "num": 55,
    "face": "0603170325589_42_90db6d602a8c552e1f27f810e6493325.jpg",
    "card title": "six of cups",
    "arcana": "minor",
    "suit": "cups",
    "core themes": "innocence, nostalgia",
    "upright keywords": "childhood, memories, familiarity, comfort, reunion",
    "reversed keywords": "living in the past, immaturity, unrealistic nostalgia",
    "shadow expression": "idealizing what once was",
    "growth edge": "honor the past without returning to it",
    "element": "water"
  },
  {
    "num": 56,
    "face": "0603170325589_43_e9d4f6d1912842da855ce7bbf6a69a1c.jpg",
    "card title": "seven of cups",
    "arcana": "minor",
    "suit": "cups",
    "core themes": "choices, illusion",
    "upright keywords": "options, fantasy, confusion, temptation, imagination",
    "reversed keywords": "clarity, focus, decision, realism",
    "shadow expression": "escaping into fantasy to avoid action",
    "growth edge": "choose one path and commit",
    "element": "water"
  },
  {
    "num": 57,
    "face": "0603170325589_44_6a1af0658104847d9b014fd63ed108f5.jpg",
    "card title": "eight of cups",
    "arcana": "minor",
    "suit": "cups",
    "core themes": "departure, seeking",
    "upright keywords": "walking away, seeking deeper meaning, release, transition",
    "reversed keywords": "avoidance, fear of change, staying stuck",
    "shadow expression": "leaving prematurely to avoid discomfort",
    "growth edge": "know when to stay and when to go",
    "element": "water"
  },
  {
    "num": 58,
    "face": "0603170325589_45_73b46e415f97a956f5a10199b1ebbdef.jpg",
    "card title": "nine of cups",
    "arcana": "minor",
    "suit": "cups",
    "core themes": "fulfillment, satisfaction",
    "upright keywords": "contentment, pleasure, gratitude, wishes fulfilled",
    "reversed keywords": "overindulgence, dissatisfaction, superficial happiness",
    "shadow expression": "confusing comfort with fulfillment",
    "growth edge": "seek deeper satisfaction",
    "element": "water"
  },
  {
    "num": 59,
    "face": "0603170325589_46_5ca9d96219727b64fe1f427b46a80cbe.jpg",
    "card title": "ten of cups",
    "arcana": "minor",
    "suit": "cups",
    "core themes": "harmony, joy",
    "upright keywords": "joy, family, alignment, happiness, unity",
    "reversed keywords": "disconnection, misalignment, tension, unrealistic expectations",
    "shadow expression": "pretending everything is fine",
    "growth edge": "build harmony through honesty",
    "element": "water"
  },
  {
    "num": 60,
    "face": "0603170325589_47_34877d455aac72367cf0eadb9f6a3c56.jpg",
    "card title": "page of cups",
    "arcana": "minor",
    "suit": "cups",
    "core themes": "curiosity, sensitivity",
    "upright keywords": "intuition, creativity, openness, surprise, emotional curiosity",
    "reversed keywords": "immaturity, insecurity, escapism, emotional avoidance",
    "shadow expression": "hiding in fantasy instead of acting",
    "growth edge": "express emotions clearly",
    "element": "water"
  },
  {
    "num": 61,
    "face": "0603170325589_48_6199bb0364076aba448e9678b3a1ca3d.jpg",
    "card title": "knight of cups",
    "arcana": "minor",
    "suit": "cups",
    "core themes": "pursuit, romance",
    "upright keywords": "charm, idealism, affection, imagination, pursuit",
    "reversed keywords": "moodiness, manipulation, unrealistic expectations, inconsistency",
    "shadow expression": "chasing fantasy over reality",
    "growth edge": "balance emotion with realism",
    "element": "water"
  },
  {
    "num": 62,
    "face": "0603170325589_49_54b0e1c53b93504ad02fa774b84bacde.jpg",
    "card title": "queen of cups",
    "arcana": "minor",
    "suit": "cups",
    "core themes": "empathy, intuition",
    "upright keywords": "compassion, intuition, care, emotional depth, calm",
    "reversed keywords": "overwhelm, martyrdom, insecurity, mood swings",
    "shadow expression": "absorbing others’ emotions",
    "growth edge": "protect emotional boundaries",
    "element": "water"
  },
  {
    "num": 63,
    "face": "0603170325589_50_5b537786818416df612720b0745a48b9.jpg",
    "card title": "king of cups",
    "arcana": "minor",
    "suit": "cups",
    "core themes": "balance, mastery",
    "upright keywords": "balance, diplomacy, maturity, emotional control, support",
    "reversed keywords": "suppression, coldness, instability, manipulation",
    "shadow expression": "hiding vulnerability behind composure",
    "growth edge": "lead with emotional integrity",
    "element": "water"
  },
  {
    "num": 64,
    "face": "0603170325589_23_94a7f432f845bc523eb67fbbc37a9be1.jpg",
    "card title": "ace of wands",
    "arcana": "minor",
    "suit": "wands",
    "core themes": "ignition, inspiration",
    "upright keywords": "new passion, creative spark, motivation, opportunity, enthusiasm",
    "reversed keywords": "creative block, delay, lack of direction, hesitation",
    "shadow expression": "waiting for permission to begin",
    "growth edge": "act on the spark before it fades",
    "element": "fire"
  },
  {
    "num": 65,
    "face": "0603170325589_24_866f4e7c2570670a64db0f031963f2de.jpg",
    "card title": "two of wands",
    "arcana": "minor",
    "suit": "wands",
    "core themes": "expansion, planning",
    "upright keywords": "future planning, decisions, ambition, progress, exploration",
    "reversed keywords": "fear of change, lack of planning, staying small, indecision",
    "shadow expression": "dreaming without acting",
    "growth edge": "commit to a direction",
    "element": "fire"
  },
  {
    "num": 66,
    "face": "0603170325589_25_d24df431069f1a7f30847a119ad66934.jpg",
    "card title": "three of wands",
    "arcana": "minor",
    "suit": "wands",
    "core themes": "foresight, momentum",
    "upright keywords": "expansion, progress, growth, waiting for results, confidence",
    "reversed keywords": "delays, obstacles, frustration, limited vision",
    "shadow expression": "expecting results without preparation",
    "growth edge": "trust the process already in motion",
    "element": "fire"
  },
  {
    "num": 67,
    "face": "0603170325589_26_9e730438f5a36003eacb58fa91178855.jpg",
    "card title": "four of wands",
    "arcana": "minor",
    "suit": "wands",
    "core themes": "celebration, stability",
    "upright keywords": "harmony, community, milestone, home, achievement",
    "reversed keywords": "instability, conflict at home, lack of support",
    "shadow expression": "celebrating prematurely",
    "growth edge": "build foundations before celebrating",
    "element": "fire"
  },
  {
    "num": 68,
    "face": "0603170325589_27_d2a089deccfec6127f07f6ca0e2f84dd.jpg",
    "card title": "five of wands",
    "arcana": "minor",
    "suit": "wands",
    "core themes": "competition, conflict",
    "upright keywords": "disagreement, rivalry, tension, challenge, chaos",
    "reversed keywords": "avoiding conflict, resolution, compromise",
    "shadow expression": "creating drama to feel alive",
    "growth edge": "channel competition into growth",
    "element": "fire"
  },
  {
    "num": 69,
    "face": "0603170325589_28_497a49a55c8c3769dd6095781ba725ee.jpg",
    "card title": "six of wands",
    "arcana": "minor",
    "suit": "wands",
    "core themes": "recognition, victory",
    "upright keywords": "success, achievement, praise, leadership, pride",
    "reversed keywords": "ego, lack of recognition, self-doubt, fall from grace",
    "shadow expression": "needing validation to feel worthy",
    "growth edge": "lead with humility",
    "element": "fire"
  },
  {
    "num": 70,
    "face": "0603170325589_29_9bcbf1dc7e5ad05b2780a1d82857e4cb.jpg",
    "card title": "seven of wands",
    "arcana": "minor",
    "suit": "wands",
    "core themes": "defense, resilience",
    "upright keywords": "standing ground, perseverance, protection, courage",
    "reversed keywords": "giving up, overwhelm, vulnerability, exhaustion",
    "shadow expression": "fighting battles that are not yours",
    "growth edge": "choose what is worth defending",
    "element": "fire"
  },
  {
    "num": 71,
    "face": "0603170325589_30_1d1f1456263bf60fadfe12231db9b403.jpg",
    "card title": "eight of wands",
    "arcana": "minor",
    "suit": "wands",
    "core themes": "movement, speed",
    "upright keywords": "fast progress, travel, communication, momentum",
    "reversed keywords": "delays, miscommunication, frustration, stagnation",
    "shadow expression": "rushing without clarity",
    "growth edge": "move quickly but intentionally",
    "element": "fire"
  },
  {
    "num": 72,
    "face": "0603170325589_31_253e6e7f3b5eb88ada02b90563d4bcf9.jpg",
    "card title": "nine of wands",
    "arcana": "minor",
    "suit": "wands",
    "core themes": "endurance, persistence",
    "upright keywords": "resilience, boundaries, last effort, fatigue, defense",
    "reversed keywords": "burnout, paranoia, giving up, stubbornness",
    "shadow expression": "refusing help out of pride",
    "growth edge": "rest before the final push",
    "element": "fire"
  },
  {
    "num": 73,
    "face": "0603170325589_32_7026f2023309f46f84866f6fcc31bc15.jpg",
    "card title": "ten of wands",
    "arcana": "minor",
    "suit": "wands",
    "core themes": "burden, responsibility",
    "upright keywords": "overwhelm, stress, pressure, hard work, duty",
    "reversed keywords": "release, delegation, breaking free, burnout",
    "shadow expression": "carrying more than you need to",
    "growth edge": "lighten your load",
    "element": "fire"
  },
  {
    "num": 74,
    "face": "0603170325589_33_31ed5cc76401b7be30b5753b45d2b95f.jpg",
    "card title": "page of wands",
    "arcana": "minor",
    "suit": "wands",
    "core themes": "curiosity, exploration",
    "upright keywords": "enthusiasm, discovery, creativity, excitement, new ideas",
    "reversed keywords": "immaturity, lack of follow-through, scattered energy",
    "shadow expression": "chasing novelty without commitment",
    "growth edge": "nurture ideas into action",
    "element": "fire"
  },
  {
    "num": 75,
    "face": "0603170325589_34_3b6053b9ffa8b117f8952672768867fc.jpg",
    "card title": "knight of wands",
    "arcana": "minor",
    "suit": "wands",
    "core themes": "bold action, intensity",
    "upright keywords": "passion, adventure, confidence, impulsiveness, drive",
    "reversed keywords": "recklessness, impatience, anger, unpredictability",
    "shadow expression": "mistaking intensity for depth",
    "growth edge": "temper passion with strategy",
    "element": "fire"
  },
  {
    "num": 76,
    "face": "0603170325589_35_ff7dea6d2fb1a739d51702c4eaaca93b.jpg",
    "card title": "queen of wands",
    "arcana": "minor",
    "suit": "wands",
    "core themes": "confidence, magnetism",
    "upright keywords": "independence, charisma, warmth, leadership, courage",
    "reversed keywords": "jealousy, insecurity, dominance, self-doubt",
    "shadow expression": "seeking control to mask insecurity",
    "growth edge": "own your presence without overpowering",
    "element": "fire"
  },
  {
    "num": 77,
    "face": "0603170325589_36_25b80e8f176c8458ea67bceaa6381416.jpg",
    "card title": "king of wands",
    "arcana": "minor",
    "suit": "wands",
    "core themes": "leadership, vision",
    "upright keywords": "authority, ambition, inspiration, strategy, influence",
    "reversed keywords": "impulsiveness, arrogance, lack of direction, control issues",
    "shadow expression": "leading without listening",
    "growth edge": "guide others with vision and restraint",
    "element": "fire"
  }
]
const deck = {};

rawDeck.forEach(card => {
  deck[card.num] = {
    name: card["card title"],
    core: card["core themes"].split(",").map(s => s.trim()),
    upright: {
      keywords: card["upright keywords"].split(",").map(s => s.trim()),
      shadow: card["shadow expression"],
      growth: card["growth edge"]
    },
    reversed: {
      keywords: card["reversed keywords"].split(",").map(s => s.trim()),
      shadow: card["shadow expression"],
      growth: card["growth edge"]
    }
  };
});
